// Copy for the premium Zakat and Portfolio Guardian landing pages, in every
// app language. House style: no dashes in copy, plain sentences a person would
// say out loud, facts that match what the app really does (see
// src/components/ZakatCalculator.jsx and src/pages/Guardian.jsx).

export const LANGS = ['en', 'ar', 'fr', 'es', 'de', 'it']

export const UI = {
  en: { langs: 'Available in 6 languages', name: 'English', features: 'Features', faq: 'FAQ', faqH: 'Questions people ask', foot: 'Free, private, no account', privacy: 'Privacy', terms: 'Terms', example: 'Example', home: 'Home', more: 'More from WalletLens', zakat: 'Zakat', guardian: 'Portfolio Guardian', ext: 'Chrome extension', calc: 'Zakat calculator', facts: 'Key facts', skip: 'Skip to content' },
  ar: { langs: 'متوفر بست لغات', name: 'العربية', features: 'المزايا', faq: 'الأسئلة', faqH: 'أسئلة شائعة', foot: 'مجاني وخاص وبلا حساب', privacy: 'الخصوصية', terms: 'الشروط', example: 'مثال', home: 'الرئيسية', more: 'المزيد من WalletLens', zakat: 'الزكاة', guardian: 'حارس المحفظة', ext: 'إضافة كروم', calc: 'حاسبة الزكاة', facts: 'حقائق سريعة', skip: 'انتقل إلى المحتوى' },
  fr: { langs: 'Disponible en 6 langues', name: 'Français', features: 'Fonctions', faq: 'FAQ', faqH: 'Questions fréquentes', foot: 'Gratuit, privé, sans compte', privacy: 'Confidentialité', terms: 'Conditions', example: 'Exemple', home: 'Accueil', more: 'Aussi chez WalletLens', zakat: 'Zakat', guardian: 'Portfolio Guardian', ext: 'Extension Chrome', calc: 'Calculateur de zakat', facts: 'En bref', skip: 'Aller au contenu' },
  es: { langs: 'Disponible en 6 idiomas', name: 'Español', features: 'Funciones', faq: 'FAQ', faqH: 'Preguntas frecuentes', foot: 'Gratis, privado, sin cuenta', privacy: 'Privacidad', terms: 'Términos', example: 'Ejemplo', home: 'Inicio', more: 'Más de WalletLens', zakat: 'Zakat', guardian: 'Portfolio Guardian', ext: 'Extensión de Chrome', calc: 'Calculadora de zakat', facts: 'Datos clave', skip: 'Ir al contenido' },
  de: { langs: 'In 6 Sprachen verfügbar', name: 'Deutsch', features: 'Funktionen', faq: 'FAQ', faqH: 'Häufige Fragen', foot: 'Kostenlos, privat, ohne Konto', privacy: 'Datenschutz', terms: 'Bedingungen', example: 'Beispiel', home: 'Start', more: 'Mehr von WalletLens', zakat: 'Zakat', guardian: 'Portfolio Guardian', ext: 'Chrome-Erweiterung', calc: 'Zakat-Rechner', facts: 'Auf einen Blick', skip: 'Zum Inhalt' },
  it: { langs: 'Disponibile in 6 lingue', name: 'Italiano', features: 'Funzioni', faq: 'FAQ', faqH: 'Domande frequenti', foot: 'Gratis, privato, senza account', privacy: 'Privacy', terms: 'Termini', example: 'Esempio', home: 'Home', more: 'Altro da WalletLens', zakat: 'Zakat', guardian: 'Portfolio Guardian', ext: 'Estensione Chrome', calc: 'Calcolatore di zakat', facts: 'In breve', skip: 'Vai al contenuto' },
}

// ── Zakat ───────────────────────────────────────────────────────────────────
export const ZAKAT = {
  en: {
    title: 'Zakat Calculator 2026 for Gold, Crypto & Stocks | WalletLens',
    desc: 'Free zakat calculator and tracker: gold, silver, cash, crypto, stocks and property at live prices, nisab checked daily, Hijri zakat year tracked, 2.5% worked out. Private, no account.',
    keywords: 'zakat calculator, zakat calculator 2026, nisab 2026, zakat on gold, zakat on crypto, zakat on stocks, zakat on shares, hawl, zakat app, zakat tracker',
    crumb: 'Zakat',
    kick: 'Free zakat calculator 2026',
    h1: 'Zakat on <em>everything you own,</em> calculated for you.',
    sub: 'Gold, silver, cash, crypto, stocks and property, priced live. WalletLens checks the nisab, tracks your zakat year on the Hijri calendar and shows exactly what is due at 2.5%. Nothing leaves your device.',
    cta: 'Calculate my zakat', cta2: 'How it works',
    trust: ['Gold or silver nisab', 'Hijri zakat year', 'Crypto and stocks', 'No account'],
    answerH: 'Zakat in one paragraph',
    answer: 'Zakat is 2.5% of the wealth a Muslim has held for one full lunar year (the hawl), once that wealth reaches the nisab: the value of 85 grams of gold or 595 grams of silver. WalletLens is a free app that adds up gold, silver, cash, crypto, stocks and investment property at live prices, deducts debts that are due, checks the result against the nisab every day and tells you the date and amount your zakat falls due.',
    facts: [['Rate', '2.5% of zakatable wealth'], ['Nisab', '85 g of gold or 595 g of silver, priced live'], ['Zakat year', 'Lunar (354 days) or solar'], ['Assets', 'Gold, silver, cash, crypto, stocks, funds, property'], ['Price', 'Free, no account'], ['Privacy', 'Calculated on your device']],
    card: { title: 'Your zakat this year', status: 'Above nisab', due: 'Zakat due', hawl: 'Zakat year (hawl): 287 of 354 days', start: '12 Muharram 1448', end: 'Due 26 Dhul Qadah 1448', gold: 'Gold, 120 g', crypto: 'Crypto', stocks: 'Stocks and funds', cash: 'Cash and savings', debts: 'Debts due', total: 'Zakatable wealth', nisab: 'Nisab, 85 g of gold' },
    howH: 'Three steps to <em>a clear answer.</em>',
    howP: 'No spreadsheets and no guessing at gold prices. Add what you own once and WalletLens keeps your zakat up to date all year.',
    steps: [
      ['Add what you own', 'Type it, say it or snap a screenshot of your bank, exchange or broker. Gold by the gram, cash in any currency.'],
      ['We price it live', 'Live gold, silver, crypto and stock prices value your wealth and compare it with the nisab every day.'],
      ['See what is due', 'The 2.5% due, the date your zakat year completes, and a reminder before it does. Mark it paid in one tap.'],
    ],
    fH: 'Built for how <em>Muslims really invest.</em>',
    feats: [
      ['coins', 'Every asset in one zakat', 'Gold, silver, cash, savings, crypto, stocks, funds and investment property, all valued in your own currency and added up for you.'],
      ['scale', 'Gold or silver nisab', 'Choose 85 g of gold or 595 g of silver. The threshold moves with live metal prices.'],
      ['moon', 'Hijri zakat year', 'Your hawl starts the day you reach nisab and is tracked on the lunar calendar, with the due date shown in Hijri.'],
      ['minus', 'Debts deducted', 'Debts that are due now come off before the 2.5% is worked out.'],
      ['chart', 'Stocks counted properly', 'Mark each holding as trading or long term so shares and property are counted the way scholars describe.'],
      ['lock', 'Private by design', 'No account and no upload. Your wealth and your zakat stay on your device. Reminders carry a date, never an amount.'],
    ],
    faq: [
      ['How much is the nisab in 2026?', 'The nisab is the value of 85 grams of gold or 595 grams of silver, so it moves with metal prices rather than being a fixed figure. WalletLens shows today’s nisab in your own currency from live prices.'],
      ['Is zakat due on crypto?', 'Most contemporary scholars treat crypto held as an investment like money or trade goods, so it counts toward the nisab at its market value on your due date. WalletLens includes it, and lets you leave it out if you follow the view that it is not zakatable.'],
      ['How is zakat on stocks calculated?', 'Shares you trade are zakatable at full market value. For shares held long term, many scholars allow zakat on the company’s zakatable assets only, commonly approximated as about 30% of market value. WalletLens lets you mark each holding.'],
      ['Should I use the gold or the silver nisab?', 'The silver nisab is lower, so more people reach it, and many zakat bodies use it for cash and mixed wealth. The gold nisab is also widely followed. Pick the one your scholar follows; you can switch at any time.'],
      ['Is zakat 2.5% or 2.577%?', 'Zakat is 2.5% on a lunar year of about 354 days. If you pay on a fixed solar date, the rate rises to 2.577% to cover the extra days. WalletLens supports both.'],
      ['Is my financial data private?', 'Yes. Everything is calculated on your device. There is no account and nothing you enter is sent to a server.'],
    ],
    note: 'WalletLens is a calculation tool, not a fatwa. Rulings differ between schools and scholars, particularly on crypto and on shares.',
    endH: 'Pay your zakat <em>with confidence.</em>',
    endP: 'Free on the web, Android, Windows and Chrome. In English, Arabic, French, Spanish, German and Italian.',
    howToName: 'How to calculate zakat on gold, crypto and stocks',
  },
  ar: {
    title: 'حاسبة الزكاة ٢٠٢٦ للذهب والعملات الرقمية والأسهم | WalletLens',
    desc: 'حاسبة ومتابع زكاة مجاني: الذهب والفضة والنقد والعملات الرقمية والأسهم والعقار بأسعار لحظية، والنصاب يُفحص يوميا، والحول الهجري متابع، ونسبة ٢٫٥٪ محسوبة. خاص وبلا حساب.',
    keywords: 'حاسبة الزكاة, نصاب الزكاة ٢٠٢٦, زكاة الذهب, زكاة العملات الرقمية, زكاة الأسهم, الحول, تطبيق الزكاة, حساب الزكاة',
    crumb: 'الزكاة',
    kick: 'حاسبة زكاة مجانية ٢٠٢٦',
    h1: 'زكاة <em>كل ما تملك،</em> محسوبة لك بدقة.',
    sub: 'الذهب والفضة والنقد والعملات الرقمية والأسهم والعقار بأسعار لحظية. يتحقق WalletLens من النصاب ويتابع حولك بالتقويم الهجري ويبين لك المستحق بنسبة ٢٫٥٪. لا شيء يغادر جهازك.',
    cta: 'احسب زكاتي', cta2: 'كيف يعمل',
    trust: ['نصاب الذهب أو الفضة', 'الحول الهجري', 'العملات الرقمية والأسهم', 'بلا حساب'],
    answerH: 'الزكاة في فقرة واحدة',
    answer: 'الزكاة ٢٫٥٪ من المال الذي ملكه المسلم حولا قمريا كاملا متى بلغ النصاب، وهو قيمة ٨٥ غراما من الذهب أو ٥٩٥ غراما من الفضة. WalletLens تطبيق مجاني يجمع الذهب والفضة والنقد والعملات الرقمية والأسهم والعقار الاستثماري بأسعار لحظية، ويخصم الديون الحالّة، ويقارن المجموع بالنصاب كل يوم، ويخبرك بتاريخ وجوب زكاتك ومقدارها.',
    facts: [['النسبة', '٢٫٥٪ من المال الزكوي'], ['النصاب', '٨٥ غرام ذهب أو ٥٩٥ غرام فضة بالسعر الحالي'], ['الحول', 'قمري (٣٥٤ يوما) أو شمسي'], ['الأصول', 'ذهب وفضة ونقد وعملات رقمية وأسهم وصناديق وعقار'], ['السعر', 'مجاني بلا حساب'], ['الخصوصية', 'الحساب على جهازك']],
    card: { title: 'زكاتك هذا العام', status: 'فوق النصاب', due: 'الزكاة المستحقة', hawl: 'الحول: ٢٨٧ من ٣٥٤ يوما', start: '١٢ محرم ١٤٤٨', end: 'تجب ٢٦ ذو القعدة ١٤٤٨', gold: 'ذهب، ١٢٠ غرام', crypto: 'عملات رقمية', stocks: 'أسهم وصناديق', cash: 'نقد ومدخرات', debts: 'ديون حالّة', total: 'المال الزكوي', nisab: 'النصاب، ٨٥ غرام ذهب' },
    howH: 'ثلاث خطوات <em>لإجابة واضحة.</em>',
    howP: 'بلا جداول ولا تخمين لأسعار الذهب. أضف ما تملكه مرة واحدة ويبقي WalletLens زكاتك محدثة طوال العام.',
    steps: [
      ['أضف ما تملك', 'اكتبه أو قله بصوتك أو التقط صورة لحسابك في البنك أو المنصة أو الوسيط. الذهب بالغرام والنقد بأي عملة.'],
      ['نسعّره لحظيا', 'أسعار الذهب والفضة والعملات الرقمية والأسهم الحية تقيّم مالك وتقارنه بالنصاب كل يوم.'],
      ['اعرف المستحق', 'مقدار ٢٫٥٪ وتاريخ تمام الحول وتذكير قبله. سجّل الدفع بلمسة واحدة.'],
    ],
    fH: 'مصمم لطريقة <em>استثمار المسلم.</em>',
    feats: [
      ['coins', 'كل أموالك في زكاة واحدة', 'الذهب والفضة والنقد والمدخرات والعملات الرقمية والأسهم والصناديق والعقار الاستثماري، بعملتك ومجموعة لك.'],
      ['scale', 'نصاب الذهب أو الفضة', 'اختر ٨٥ غرام ذهب أو ٥٩٥ غرام فضة، ويتحرك النصاب مع أسعار المعادن.'],
      ['moon', 'الحول الهجري', 'يبدأ حولك يوم بلوغ النصاب ويُتابَع بالتقويم القمري مع تاريخ الوجوب بالهجري.'],
      ['minus', 'خصم الديون', 'تُخصم الديون الحالّة قبل حساب ٢٫٥٪.'],
      ['chart', 'الأسهم بالطريقة الصحيحة', 'حدد كل سهم للمتاجرة أو للاقتناء الطويل لتُحسب الأسهم والعقار كما بيّن العلماء.'],
      ['lock', 'خصوصية تامة', 'بلا حساب وبلا رفع بيانات. ثروتك وزكاتك تبقى على جهازك، والتذكير يحمل تاريخا لا مبلغا.'],
    ],
    faq: [
      ['كم نصاب الزكاة في ٢٠٢٦؟', 'النصاب قيمة ٨٥ غراما من الذهب أو ٥٩٥ غراما من الفضة، فهو يتغير بتغير سعر المعدن. ويعرض WalletLens نصاب اليوم بعملتك من الأسعار الحية.'],
      ['هل تجب الزكاة في العملات الرقمية؟', 'يرى أكثر المعاصرين أن العملات الرقمية المقتناة للاستثمار كالنقد أو عروض التجارة، فتُحسب بقيمتها السوقية يوم الوجوب. ويشملها WalletLens ويتيح لك استبعادها إن كنت تتبع القول بعدم زكاتها.'],
      ['كيف تُحسب زكاة الأسهم؟', 'أسهم المتاجرة تُزكّى بقيمتها السوقية كاملة، وأسهم الاقتناء الطويل يجيز كثير من العلماء زكاة الموجودات الزكوية للشركة فقط، والتقدير الشائع نحو ٣٠٪ من القيمة السوقية. ويتيح لك WalletLens تحديد كل سهم.'],
      ['نصاب الذهب أم الفضة؟', 'نصاب الفضة أقل فيبلغه عدد أكبر، وتعتمده جهات زكاة كثيرة للنقد والمال المختلط، ونصاب الذهب معمول به أيضا. اختر ما يتبعه عالمك، ويمكنك التغيير متى شئت.'],
      ['أهي ٢٫٥٪ أم ٢٫٥٧٧٪؟', '٢٫٥٪ على الحول القمري نحو ٣٥٤ يوما، فإن أخرجت على تاريخ شمسي ثابت رُفعت النسبة إلى ٢٫٥٧٧٪ لتغطية الأيام الزائدة. ويدعم WalletLens الحالتين.'],
      ['هل بياناتي المالية خاصة؟', 'نعم. كل الحساب يتم على جهازك، بلا حساب، ولا يُرسل شيء مما تدخله إلى أي خادم.'],
    ],
    note: 'WalletLens أداة حساب لا فتوى. تختلف الأقوال بين المذاهب والعلماء، خاصة في العملات الرقمية والأسهم.',
    endH: 'أدِّ زكاتك <em>بطمأنينة.</em>',
    endP: 'مجاني على الويب وأندرويد وويندوز وكروم، بالعربية والإنجليزية والفرنسية والإسبانية والألمانية والإيطالية.',
    howToName: 'كيف تحسب زكاة الذهب والعملات الرقمية والأسهم',
  },
  fr: {
    title: 'Calculateur de zakat 2026 : or, crypto et actions | WalletLens',
    desc: 'Calculateur de zakat gratuit : or, argent, liquidités, crypto, actions et immobilier au prix du marché, nisab vérifié chaque jour, année hégirienne suivie, 2,5 % calculés. Privé, sans compte.',
    keywords: 'calculateur zakat, calcul zakat 2026, nisab 2026, zakat sur l’or, zakat crypto, zakat actions, hawl, application zakat',
    crumb: 'Zakat',
    kick: 'Calculateur de zakat gratuit',
    h1: 'La zakat sur <em>tout ce que vous possédez,</em> calculée pour vous.',
    sub: 'Or, argent, liquidités, crypto, actions et immobilier, au prix du marché. WalletLens vérifie le nisab, suit votre année de zakat sur le calendrier hégirien et indique exactement ce qui est dû à 2,5 %. Rien ne quitte votre appareil.',
    cta: 'Calculer ma zakat', cta2: 'Comment ça marche',
    trust: ['Nisab or ou argent', 'Année hégirienne', 'Crypto et actions', 'Sans compte'],
    answerH: 'La zakat en un paragraphe',
    answer: 'La zakat représente 2,5 % des biens qu’un musulman détient depuis une année lunaire complète (le hawl), dès que ces biens atteignent le nisab : la valeur de 85 grammes d’or ou de 595 grammes d’argent. WalletLens est une application gratuite qui additionne or, argent, liquidités, crypto, actions et immobilier locatif au prix du marché, déduit les dettes exigibles, compare le total au nisab chaque jour et vous indique la date et le montant de votre zakat.',
    facts: [['Taux', '2,5 % des biens soumis à la zakat'], ['Nisab', '85 g d’or ou 595 g d’argent, au prix du jour'], ['Année de zakat', 'Lunaire (354 jours) ou solaire'], ['Actifs', 'Or, argent, liquidités, crypto, actions, fonds, immobilier'], ['Prix', 'Gratuit, sans compte'], ['Confidentialité', 'Calcul sur votre appareil']],
    card: { title: 'Votre zakat cette année', status: 'Au-dessus du nisab', due: 'Zakat due', hawl: 'Année de zakat (hawl) : 287 sur 354 jours', start: '12 Muharram 1448', end: 'Due le 26 Dhou al Qi’da 1448', gold: 'Or, 120 g', crypto: 'Crypto', stocks: 'Actions et fonds', cash: 'Liquidités et épargne', debts: 'Dettes exigibles', total: 'Biens soumis à la zakat', nisab: 'Nisab, 85 g d’or' },
    howH: 'Trois étapes pour <em>une réponse claire.</em>',
    howP: 'Ni tableur ni cours de l’or à deviner. Ajoutez vos biens une fois et WalletLens tient votre zakat à jour toute l’année.',
    steps: [
      ['Ajoutez vos biens', 'Tapez, dictez ou faites une capture de votre banque, plateforme ou courtier. L’or au gramme, les liquidités dans toute devise.'],
      ['Valorisés en direct', 'Les cours de l’or, de l’argent, de la crypto et des actions valorisent vos biens et les comparent au nisab chaque jour.'],
      ['Voyez ce qui est dû', 'Les 2,5 % dus, la date de fin de votre année de zakat et un rappel avant. Marquez la zakat payée d’un geste.'],
    ],
    fH: 'Pensé pour la façon dont <em>les musulmans investissent.</em>',
    feats: [
      ['coins', 'Tous vos biens, une seule zakat', 'Or, argent, liquidités, épargne, crypto, actions, fonds et immobilier locatif, valorisés dans votre devise et additionnés pour vous.'],
      ['scale', 'Nisab or ou argent', 'Choisissez 85 g d’or ou 595 g d’argent. Le seuil suit le cours des métaux.'],
      ['moon', 'Année hégirienne', 'Votre hawl commence le jour où vous atteignez le nisab et suit le calendrier lunaire, avec la date due en hégirien.'],
      ['minus', 'Dettes déduites', 'Les dettes exigibles sont retirées avant le calcul des 2,5 %.'],
      ['chart', 'Actions bien comptées', 'Indiquez si chaque ligne est détenue pour le négoce ou à long terme, comme le décrivent les savants.'],
      ['lock', 'Privé par conception', 'Ni compte ni envoi. Vos biens et votre zakat restent sur votre appareil. Les rappels portent une date, jamais un montant.'],
    ],
    faq: [
      ['Quel est le nisab en 2026 ?', 'Le nisab est la valeur de 85 grammes d’or ou de 595 grammes d’argent : il varie donc avec le cours des métaux. WalletLens affiche le nisab du jour dans votre devise.'],
      ['La zakat est-elle due sur la crypto ?', 'La plupart des savants contemporains assimilent la crypto détenue comme placement à de l’argent ou à une marchandise : elle compte pour sa valeur de marché le jour dû. WalletLens l’inclut et permet de l’exclure si vous suivez l’avis contraire.'],
      ['Comment calculer la zakat sur les actions ?', 'Les actions détenues pour le négoce comptent pour leur pleine valeur. Pour les placements à long terme, beaucoup de savants retiennent les seuls actifs zakatables de l’entreprise, soit environ 30 % de la valeur de marché. WalletLens vous laisse choisir pour chaque ligne.'],
      ['Nisab or ou nisab argent ?', 'Le nisab argent est plus bas, donc atteint par davantage de personnes, et de nombreux organismes l’utilisent pour l’argent liquide. Le nisab or est aussi largement suivi. Choisissez celui de votre savant ; vous pouvez changer à tout moment.'],
      ['2,5 % ou 2,577 % ?', 'La zakat est de 2,5 % sur une année lunaire d’environ 354 jours. Si vous payez à une date solaire fixe, le taux passe à 2,577 % pour couvrir les jours en plus. WalletLens gère les deux.'],
      ['Mes données sont-elles privées ?', 'Oui. Tout est calculé sur votre appareil, sans compte, et rien de ce que vous saisissez n’est envoyé à un serveur.'],
    ],
    note: 'WalletLens est un outil de calcul, pas une fatwa. Les avis diffèrent selon les écoles et les savants, notamment sur la crypto et les actions.',
    endH: 'Payez votre zakat <em>en toute confiance.</em>',
    endP: 'Gratuit sur le web, Android, Windows et Chrome. En français, anglais, arabe, espagnol, allemand et italien.',
    howToName: 'Comment calculer la zakat sur l’or, la crypto et les actions',
  },
  es: {
    title: 'Calculadora de zakat 2026: oro, cripto y acciones | WalletLens',
    desc: 'Calculadora de zakat gratis: oro, plata, efectivo, cripto, acciones e inmuebles a precio real, nisab comprobado a diario, año hégira seguido y el 2,5 % calculado. Privado, sin cuenta.',
    keywords: 'calculadora zakat, zakat 2026, nisab 2026, zakat sobre el oro, zakat cripto, zakat acciones, hawl, app de zakat',
    crumb: 'Zakat',
    kick: 'Calculadora de zakat gratis',
    h1: 'El zakat de <em>todo lo que tienes,</em> calculado por ti.',
    sub: 'Oro, plata, efectivo, cripto, acciones e inmuebles a precio real. WalletLens comprueba el nisab, sigue tu año de zakat en el calendario hégira y muestra exactamente lo que debes al 2,5 %. Nada sale de tu dispositivo.',
    cta: 'Calcular mi zakat', cta2: 'Cómo funciona',
    trust: ['Nisab de oro o plata', 'Año hégira', 'Cripto y acciones', 'Sin cuenta'],
    answerH: 'El zakat en un párrafo',
    answer: 'El zakat es el 2,5 % de los bienes que un musulmán ha tenido durante un año lunar completo (el hawl), cuando esos bienes alcanzan el nisab: el valor de 85 gramos de oro o 595 gramos de plata. WalletLens es una app gratuita que suma oro, plata, efectivo, cripto, acciones e inmuebles de inversión a precio real, resta las deudas vencidas, compara el total con el nisab cada día y te dice la fecha y el importe de tu zakat.',
    facts: [['Tasa', '2,5 % de los bienes sujetos a zakat'], ['Nisab', '85 g de oro o 595 g de plata, a precio real'], ['Año de zakat', 'Lunar (354 días) o solar'], ['Activos', 'Oro, plata, efectivo, cripto, acciones, fondos, inmuebles'], ['Precio', 'Gratis, sin cuenta'], ['Privacidad', 'Se calcula en tu dispositivo']],
    card: { title: 'Tu zakat este año', status: 'Sobre el nisab', due: 'Zakat a pagar', hawl: 'Año de zakat (hawl): 287 de 354 días', start: '12 Muharram 1448', end: 'Vence 26 Dhul Qadah 1448', gold: 'Oro, 120 g', crypto: 'Cripto', stocks: 'Acciones y fondos', cash: 'Efectivo y ahorro', debts: 'Deudas vencidas', total: 'Bienes sujetos a zakat', nisab: 'Nisab, 85 g de oro' },
    howH: 'Tres pasos para <em>una respuesta clara.</em>',
    howP: 'Sin hojas de cálculo ni adivinar el precio del oro. Añade lo que tienes una vez y WalletLens mantiene tu zakat al día todo el año.',
    steps: [
      ['Añade lo que tienes', 'Escríbelo, dilo o haz una captura de tu banco, exchange o bróker. El oro por gramos, el efectivo en cualquier moneda.'],
      ['Precio en tiempo real', 'Los precios del oro, la plata, las cripto y las acciones valoran tus bienes y los comparan con el nisab cada día.'],
      ['Mira lo que debes', 'El 2,5 % a pagar, la fecha en que se cumple tu año y un aviso antes. Márcalo pagado con un toque.'],
    ],
    fH: 'Hecho para cómo <em>invierten los musulmanes.</em>',
    feats: [
      ['coins', 'Todos tus bienes, un solo zakat', 'Oro, plata, efectivo, ahorro, cripto, acciones, fondos e inmuebles de inversión, en tu propia moneda y sumados por ti.'],
      ['scale', 'Nisab de oro o plata', 'Elige 85 g de oro o 595 g de plata. El umbral sigue el precio de los metales.'],
      ['moon', 'Año hégira', 'Tu hawl empieza el día que alcanzas el nisab y se sigue en el calendario lunar, con la fecha en hégira.'],
      ['minus', 'Deudas descontadas', 'Las deudas vencidas se restan antes de calcular el 2,5 %.'],
      ['chart', 'Acciones bien contadas', 'Marca cada posición como de trading o de largo plazo, tal como lo describen los sabios.'],
      ['lock', 'Privado por diseño', 'Sin cuenta y sin subir nada. Tus bienes y tu zakat se quedan en tu dispositivo. Los avisos llevan una fecha, nunca un importe.'],
    ],
    faq: [
      ['¿Cuál es el nisab en 2026?', 'El nisab es el valor de 85 gramos de oro o 595 gramos de plata, así que cambia con el precio de los metales. WalletLens muestra el nisab de hoy en tu moneda.'],
      ['¿Hay zakat sobre las cripto?', 'La mayoría de los sabios actuales tratan las cripto de inversión como dinero o mercancía, así que cuentan por su valor de mercado el día del pago. WalletLens las incluye y te deja excluirlas si sigues la opinión contraria.'],
      ['¿Cómo se calcula el zakat de las acciones?', 'Las acciones de trading cuentan por su valor de mercado completo. Para las de largo plazo, muchos sabios aceptan solo los activos zakatables de la empresa, aproximadamente un 30 % del valor de mercado. WalletLens te deja marcar cada una.'],
      ['¿Nisab de oro o de plata?', 'El nisab de plata es más bajo, así que más personas lo alcanzan, y muchas entidades lo usan para el efectivo. El de oro también se sigue mucho. Elige el de tu sabio; puedes cambiarlo cuando quieras.'],
      ['¿2,5 % o 2,577 %?', 'El zakat es del 2,5 % sobre un año lunar de unos 354 días. Si pagas en una fecha solar fija, la tasa sube al 2,577 % para cubrir los días extra. WalletLens admite ambas.'],
      ['¿Mis datos son privados?', 'Sí. Todo se calcula en tu dispositivo, sin cuenta, y nada de lo que introduces se envía a un servidor.'],
    ],
    note: 'WalletLens es una herramienta de cálculo, no una fatwa. Las opiniones varían entre escuelas y sabios, sobre todo en cripto y acciones.',
    endH: 'Paga tu zakat <em>con tranquilidad.</em>',
    endP: 'Gratis en la web, Android, Windows y Chrome. En español, inglés, árabe, francés, alemán e italiano.',
    howToName: 'Cómo calcular el zakat del oro, las cripto y las acciones',
  },
  de: {
    title: 'Zakat-Rechner 2026 für Gold, Krypto & Aktien | WalletLens',
    desc: 'Kostenloser Zakat-Rechner: Gold, Silber, Bargeld, Krypto, Aktien und Immobilien zu Live-Preisen, Nisab täglich geprüft, Hidschra-Jahr verfolgt, 2,5 % berechnet. Privat, ohne Konto.',
    keywords: 'Zakat-Rechner, Zakat berechnen 2026, Nisab 2026, Zakat auf Gold, Zakat Krypto, Zakat Aktien, Hawl, Zakat-App',
    crumb: 'Zakat',
    kick: 'Kostenloser Zakat-Rechner',
    h1: 'Zakat auf <em>alles, was Sie besitzen,</em> für Sie berechnet.',
    sub: 'Gold, Silber, Bargeld, Krypto, Aktien und Immobilien zu Live-Preisen. WalletLens prüft den Nisab, verfolgt Ihr Zakat-Jahr im Hidschra-Kalender und zeigt genau, was bei 2,5 % fällig ist. Nichts verlässt Ihr Gerät.',
    cta: 'Meine Zakat berechnen', cta2: 'So funktioniert es',
    trust: ['Gold- oder Silber-Nisab', 'Hidschra-Jahr', 'Krypto und Aktien', 'Ohne Konto'],
    answerH: 'Zakat in einem Absatz',
    answer: 'Zakat sind 2,5 % des Vermögens, das ein Muslim ein volles Mondjahr (den Hawl) besessen hat, sobald es den Nisab erreicht: den Wert von 85 Gramm Gold oder 595 Gramm Silber. WalletLens ist eine kostenlose App, die Gold, Silber, Bargeld, Krypto, Aktien und vermietete Immobilien zu Live-Preisen addiert, fällige Schulden abzieht, die Summe täglich mit dem Nisab vergleicht und Ihnen Datum und Betrag Ihrer Zakat nennt.',
    facts: [['Satz', '2,5 % des zakatpflichtigen Vermögens'], ['Nisab', '85 g Gold oder 595 g Silber, live bewertet'], ['Zakat-Jahr', 'Mondjahr (354 Tage) oder Sonnenjahr'], ['Werte', 'Gold, Silber, Bargeld, Krypto, Aktien, Fonds, Immobilien'], ['Preis', 'Kostenlos, ohne Konto'], ['Datenschutz', 'Berechnung auf Ihrem Gerät']],
    card: { title: 'Ihre Zakat dieses Jahr', status: 'Über dem Nisab', due: 'Fällige Zakat', hawl: 'Zakat-Jahr (Hawl): 287 von 354 Tagen', start: '12. Muharram 1448', end: 'Fällig 26. Dhu l Qa’da 1448', gold: 'Gold, 120 g', crypto: 'Krypto', stocks: 'Aktien und Fonds', cash: 'Bargeld und Ersparnisse', debts: 'Fällige Schulden', total: 'Zakatpflichtiges Vermögen', nisab: 'Nisab, 85 g Gold' },
    howH: 'Drei Schritte zu <em>einer klaren Antwort.</em>',
    howP: 'Keine Tabellen und kein Raten beim Goldpreis. Erfassen Sie Ihr Vermögen einmal, und WalletLens hält Ihre Zakat das ganze Jahr aktuell.',
    steps: [
      ['Vermögen erfassen', 'Tippen, sprechen oder einen Screenshot von Bank, Börse oder Broker machen. Gold in Gramm, Bargeld in jeder Währung.'],
      ['Live bewertet', 'Aktuelle Preise für Gold, Silber, Krypto und Aktien bewerten Ihr Vermögen und vergleichen es täglich mit dem Nisab.'],
      ['Sehen, was fällig ist', 'Die fälligen 2,5 %, das Ende Ihres Zakat-Jahres und eine Erinnerung davor. Mit einem Tipp als bezahlt markieren.'],
    ],
    fH: 'Gemacht dafür, wie <em>Muslime wirklich investieren.</em>',
    feats: [
      ['coins', 'Alles in einer Zakat', 'Gold, Silber, Bargeld, Ersparnisse, Krypto, Aktien, Fonds und vermietete Immobilien, in Ihrer Währung bewertet und für Sie addiert.'],
      ['scale', 'Gold- oder Silber-Nisab', 'Wählen Sie 85 g Gold oder 595 g Silber. Die Schwelle folgt den Metallpreisen.'],
      ['moon', 'Hidschra-Jahr', 'Ihr Hawl beginnt an dem Tag, an dem Sie den Nisab erreichen, und läuft im Mondkalender, mit Fälligkeit nach Hidschra.'],
      ['minus', 'Schulden abgezogen', 'Fällige Schulden werden abgezogen, bevor die 2,5 % berechnet werden.'],
      ['chart', 'Aktien richtig gezählt', 'Markieren Sie jede Position als Handel oder langfristig, so wie es die Gelehrten beschreiben.'],
      ['lock', 'Privat von Grund auf', 'Kein Konto und kein Upload. Ihr Vermögen und Ihre Zakat bleiben auf Ihrem Gerät. Erinnerungen enthalten ein Datum, nie einen Betrag.'],
    ],
    faq: [
      ['Wie hoch ist der Nisab 2026?', 'Der Nisab ist der Wert von 85 Gramm Gold oder 595 Gramm Silber und bewegt sich daher mit den Metallpreisen. WalletLens zeigt den heutigen Nisab in Ihrer Währung.'],
      ['Ist auf Krypto Zakat fällig?', 'Die meisten heutigen Gelehrten behandeln Krypto als Anlage wie Geld oder Handelsware, sie zählt also mit ihrem Marktwert am Fälligkeitstag. WalletLens bezieht sie ein und lässt Sie sie ausschließen, wenn Sie der Gegenansicht folgen.'],
      ['Wie berechnet man Zakat auf Aktien?', 'Aktien zum Handeln zählen mit vollem Marktwert. Bei langfristigen Anlagen erlauben viele Gelehrte nur die zakatpflichtigen Werte des Unternehmens, üblich sind etwa 30 % des Marktwerts. WalletLens lässt Sie jede Position einordnen.'],
      ['Gold- oder Silber-Nisab?', 'Der Silber-Nisab ist niedriger, also erreichen ihn mehr Menschen, und viele Zakat-Stellen nutzen ihn für Bargeld. Der Gold-Nisab ist ebenfalls verbreitet. Wählen Sie den Ihres Gelehrten; Sie können jederzeit wechseln.'],
      ['2,5 % oder 2,577 %?', 'Zakat beträgt 2,5 % auf ein Mondjahr von etwa 354 Tagen. Zahlen Sie zu einem festen Sonnendatum, steigt der Satz auf 2,577 %, um die zusätzlichen Tage abzudecken. WalletLens unterstützt beides.'],
      ['Sind meine Daten privat?', 'Ja. Alles wird auf Ihrem Gerät berechnet, ohne Konto, und nichts von Ihren Eingaben wird an einen Server gesendet.'],
    ],
    note: 'WalletLens ist ein Rechenwerkzeug, keine Fatwa. Die Ansichten unterscheiden sich zwischen Rechtsschulen und Gelehrten, besonders bei Krypto und Aktien.',
    endH: 'Zahlen Sie Ihre Zakat <em>mit gutem Gefühl.</em>',
    endP: 'Kostenlos im Web, für Android, Windows und Chrome. Auf Deutsch, Englisch, Arabisch, Französisch, Spanisch und Italienisch.',
    howToName: 'So berechnen Sie Zakat auf Gold, Krypto und Aktien',
  },
  it: {
    title: 'Calcolatore di zakat 2026 per oro, cripto e azioni | WalletLens',
    desc: 'Calcolatore di zakat gratuito: oro, argento, contanti, cripto, azioni e immobili a prezzi live, nisab verificato ogni giorno, anno egiriano seguito, 2,5 % calcolato. Privato, senza account.',
    keywords: 'calcolatore zakat, calcolo zakat 2026, nisab 2026, zakat sull’oro, zakat cripto, zakat azioni, hawl, app zakat',
    crumb: 'Zakat',
    kick: 'Calcolatore di zakat gratuito',
    h1: 'La zakat su <em>tutto ciò che possiedi,</em> calcolata per te.',
    sub: 'Oro, argento, contanti, cripto, azioni e immobili a prezzi live. WalletLens verifica il nisab, segue il tuo anno di zakat sul calendario egiriano e mostra esattamente quanto è dovuto al 2,5 %. Nulla lascia il tuo dispositivo.',
    cta: 'Calcola la mia zakat', cta2: 'Come funziona',
    trust: ['Nisab oro o argento', 'Anno egiriano', 'Cripto e azioni', 'Senza account'],
    answerH: 'La zakat in un paragrafo',
    answer: 'La zakat è il 2,5 % dei beni che un musulmano possiede da un anno lunare intero (lo hawl), quando quei beni raggiungono il nisab: il valore di 85 grammi d’oro o 595 grammi d’argento. WalletLens è un’app gratuita che somma oro, argento, contanti, cripto, azioni e immobili da investimento a prezzi live, sottrae i debiti scaduti, confronta il totale con il nisab ogni giorno e ti dice data e importo della tua zakat.',
    facts: [['Aliquota', '2,5 % dei beni soggetti a zakat'], ['Nisab', '85 g d’oro o 595 g d’argento, a prezzi live'], ['Anno di zakat', 'Lunare (354 giorni) o solare'], ['Beni', 'Oro, argento, contanti, cripto, azioni, fondi, immobili'], ['Prezzo', 'Gratis, senza account'], ['Privacy', 'Calcolo sul tuo dispositivo']],
    card: { title: 'La tua zakat quest’anno', status: 'Sopra il nisab', due: 'Zakat dovuta', hawl: 'Anno di zakat (hawl): 287 di 354 giorni', start: '12 Muharram 1448', end: 'Scade 26 Dhul Qa’da 1448', gold: 'Oro, 120 g', crypto: 'Cripto', stocks: 'Azioni e fondi', cash: 'Contanti e risparmi', debts: 'Debiti scaduti', total: 'Beni soggetti a zakat', nisab: 'Nisab, 85 g d’oro' },
    howH: 'Tre passi per <em>una risposta chiara.</em>',
    howP: 'Niente fogli di calcolo e niente prezzi dell’oro da indovinare. Aggiungi ciò che possiedi una volta e WalletLens tiene aggiornata la tua zakat tutto l’anno.',
    steps: [
      ['Aggiungi ciò che possiedi', 'Scrivilo, dillo o fai uno screenshot di banca, exchange o broker. L’oro in grammi, i contanti in ogni valuta.'],
      ['Prezzi in tempo reale', 'I prezzi live di oro, argento, cripto e azioni valutano i tuoi beni e li confrontano con il nisab ogni giorno.'],
      ['Vedi quanto è dovuto', 'Il 2,5 % dovuto, la data di fine del tuo anno di zakat e un promemoria prima. Segnala pagata con un tocco.'],
    ],
    fH: 'Pensato per come <em>investono davvero i musulmani.</em>',
    feats: [
      ['coins', 'Tutti i beni, una sola zakat', 'Oro, argento, contanti, risparmi, cripto, azioni, fondi e immobili da investimento, nella tua valuta e sommati per te.'],
      ['scale', 'Nisab oro o argento', 'Scegli 85 g d’oro o 595 g d’argento. La soglia segue i prezzi dei metalli.'],
      ['moon', 'Anno egiriano', 'Il tuo hawl inizia il giorno in cui raggiungi il nisab e segue il calendario lunare, con la scadenza in data egiriana.'],
      ['minus', 'Debiti dedotti', 'I debiti scaduti vengono sottratti prima del calcolo del 2,5 %.'],
      ['chart', 'Azioni contate bene', 'Indica ogni posizione come trading o lungo termine, come descrivono i sapienti.'],
      ['lock', 'Privato per scelta', 'Nessun account e nessun caricamento. I tuoi beni e la tua zakat restano sul dispositivo. I promemoria hanno una data, mai un importo.'],
    ],
    faq: [
      ['Quanto è il nisab nel 2026?', 'Il nisab è il valore di 85 grammi d’oro o 595 grammi d’argento, quindi cambia con i prezzi dei metalli. WalletLens mostra il nisab di oggi nella tua valuta.'],
      ['La zakat è dovuta sulle cripto?', 'La maggior parte dei sapienti contemporanei tratta le cripto da investimento come denaro o merce, quindi contano al valore di mercato alla scadenza. WalletLens le include e ti permette di escluderle se segui il parere contrario.'],
      ['Come si calcola la zakat sulle azioni?', 'Le azioni di trading contano per il pieno valore di mercato. Per quelle a lungo termine molti sapienti considerano solo i beni zakatabili della società, circa il 30 % del valore di mercato. WalletLens ti fa scegliere per ogni posizione.'],
      ['Nisab oro o nisab argento?', 'Il nisab argento è più basso, quindi lo raggiungono più persone, e molti enti lo usano per il contante. Anche il nisab oro è molto seguito. Scegli quello del tuo sapiente; puoi cambiarlo quando vuoi.'],
      ['2,5 % o 2,577 %?', 'La zakat è il 2,5 % su un anno lunare di circa 354 giorni. Se paghi a una data solare fissa, l’aliquota sale al 2,577 % per coprire i giorni in più. WalletLens supporta entrambe.'],
      ['I miei dati sono privati?', 'Sì. Tutto viene calcolato sul tuo dispositivo, senza account, e nulla di ciò che inserisci viene inviato a un server.'],
    ],
    note: 'WalletLens è uno strumento di calcolo, non una fatwa. I pareri variano tra scuole e sapienti, in particolare su cripto e azioni.',
    endH: 'Paga la tua zakat <em>con serenità.</em>',
    endP: 'Gratis sul web, Android, Windows e Chrome. In italiano, inglese, arabo, francese, spagnolo e tedesco.',
    howToName: 'Come calcolare la zakat su oro, cripto e azioni',
  },
}

// ── Portfolio Guardian ──────────────────────────────────────────────────────
export const GUARDIAN = {
  en: {
    title: 'Portfolio Guardian: Crypto Inheritance & Dead Man’s Switch | WalletLens',
    desc: 'A free dead man’s switch for your investments. If you stop opening WalletLens, your heirs get your message and a QR of your crypto, stocks and gold. Never your keys.',
    keywords: 'crypto inheritance, dead man’s switch crypto, crypto inheritance plan, what happens to my crypto when I die, digital asset inheritance, portfolio dead man’s switch, crypto estate planning',
    crumb: 'Portfolio Guardian',
    kick: 'Crypto inheritance, made simple',
    h1: 'If something happens to you, <em>your family will know.</em>',
    sub: 'Portfolio Guardian is a dead man’s switch for your investments. If you stop opening WalletLens for 30, 90 or 180 days, the people you choose receive your personal message and a QR of your portfolio. Never your keys or passwords.',
    cta: 'Turn on Guardian', cta2: 'See how it works',
    trust: ['Up to 3 heirs', 'You are warned first', 'No keys shared', 'Free'],
    answerH: 'Portfolio Guardian in one paragraph',
    answer: 'Portfolio Guardian is a free dead man’s switch in the WalletLens app. You name up to three people and choose an interval of 30, 90 or 180 days. Every time you open WalletLens the countdown resets. If it runs out, WalletLens first emails you an “I’m still here” link; only if you do not answer within 14 days do your heirs receive your personal message and a scannable QR of your holdings (assets, amounts and cost basis). Private keys, seed phrases and passwords are never stored or sent.',
    facts: [['What it is', 'A dead man’s switch for your portfolio'], ['Heirs', 'Up to 3 people, by email'], ['Interval', '30, 90 or 180 days'], ['Safety net', 'You are warned first, heirs only after 14 days'], ['Shared', 'Message plus a QR of assets, amounts, cost basis'], ['Never shared', 'Keys, seed phrases, passwords']],
    card: { title: 'Portfolio Guardian', status: 'Active', days: 'days left', reset: 'Opening WalletLens resets the countdown', h1: 'Sara, wife', h2: 'Omar, son', h3: 'Layla, lawyer', r: 'Message and QR', msg: 'Personal message, keys never included' },
    howH: 'Set it once. <em>Forget it.</em>',
    howP: 'Crypto and brokerage accounts are lost every year because nobody knew they existed. Guardian makes sure the people you love can find what you leave them.',
    steps: [
      ['Choose your heirs', 'Add up to three people by name and email, and write them a personal message.'],
      ['Pick an interval', '30, 90 or 180 days. Every time you open WalletLens, the countdown starts again.'],
      ['Live your life', 'A shield in your dashboard shows the days left. There is nothing to remember.'],
    ],
    tlH: 'Nobody is ever <em>contacted by mistake.</em>',
    tlP: 'Lost your phone or away on a long trip? Guardian always asks you first, by email, from any device.',
    tl: [
      ['You go quiet', 'You have not opened WalletLens for your chosen interval.'],
      ['We email you first', 'A warning with a one click “I’m still here” link that works anywhere.'],
      ['14 days to answer', 'One click and everything resets. Your heirs never hear a thing.'],
      ['Heirs are notified', 'Only then do they receive your message and the portfolio QR.'],
    ],
    shared: ['Assets, amounts, cost basis', 'Your personal message'],
    never: ['Private keys', 'Seed phrases', 'Passwords'],
    fH: 'Peace of mind, <em>without giving anything away.</em>',
    feats: [
      ['shield', 'A real dead man’s switch', 'Runs on its own in the background. Opening the app is your check in, so it never nags you.'],
      ['mail', 'A message in your words', 'Up to 500 characters for the people you love, delivered with your portfolio.'],
      ['qr', 'Scannable portfolio QR', 'Heirs scan it to see every asset, amount and cost basis in WalletLens, so nothing is forgotten.'],
      ['key', 'Keys never leave you', 'The QR holds a snapshot of holdings only. No keys, seed phrases or passwords, ever.'],
      ['test', 'Send yourself a test', 'Preview exactly what your heirs would receive before you rely on it.'],
      ['pause', 'Cancel any time', 'Turn it off or edit your heirs in Settings whenever you like.'],
    ],
    faq: [
      ['What is a crypto dead man’s switch?', 'A service that acts when you stop checking in. Portfolio Guardian emails your heirs your message and a portfolio QR if you stop opening WalletLens for 30, 90 or 180 days.'],
      ['What happens to my crypto when I die?', 'Your coins stay where they are, but your family can only claim them if they know they exist and where to look. Guardian gives them that map: every asset, amount and platform, so they can claim it through the proper legal route.'],
      ['Will my heirs get my private keys?', 'No. Guardian never stores or sends keys, seed phrases or passwords. It tells your family what you hold and where; custody stays exactly where it is.'],
      ['What if I lose my phone or go travelling?', 'Before any heir is contacted, we email you a warning with an “I’m still here” link that works from any device. Your heirs are notified only if you do not respond for 14 days.'],
      ['Does it cover stocks, gold and cash too?', 'Yes. The snapshot covers everything in WalletLens: crypto, stocks, funds, gold, cash and property.'],
      ['Is Portfolio Guardian free?', 'Yes. It is free, with no account beyond the email addresses you choose to add.'],
    ],
    note: 'Portfolio Guardian is not a will and does not transfer ownership. Talk to a lawyer about your estate; Guardian makes sure your family knows what to ask for.',
    endH: 'Leave a map, <em>not a mystery.</em>',
    endP: 'Free on the web, Android, Windows and Chrome. In English, Arabic, French, Spanish, German and Italian.',
    howToName: 'How to set up a crypto inheritance plan with Portfolio Guardian',
  },
  ar: {
    title: 'حارس المحفظة: ميراث العملات الرقمية ومفتاح الأمان | WalletLens',
    desc: 'مفتاح أمان مجاني لاستثماراتك. إن توقفت عن فتح WalletLens يصل لورثتك رسالتك ورمز QR لعملاتك الرقمية وأسهمك وذهبك، ولا تُرسل مفاتيحك أبدا.',
    keywords: 'ميراث العملات الرقمية, ماذا يحدث لعملاتي الرقمية بعد الوفاة, مفتاح الرجل الميت, وصية العملات الرقمية, توريث الأصول الرقمية, حارس المحفظة',
    crumb: 'حارس المحفظة',
    kick: 'ميراث العملات الرقمية ببساطة',
    h1: 'إن حدث لك مكروه، <em>ستعرف عائلتك.</em>',
    sub: 'حارس المحفظة مفتاح أمان لاستثماراتك. إن توقفت عن فتح WalletLens مدة ٣٠ أو ٩٠ أو ١٨٠ يوما، يصل لمن تختارهم رسالتك الشخصية ورمز QR لمحفظتك. ولا تُرسل مفاتيحك أو كلمات مرورك أبدا.',
    cta: 'فعّل الحارس', cta2: 'شاهد كيف يعمل',
    trust: ['حتى ٣ ورثة', 'ننبهك أولا', 'بلا مفاتيح', 'مجاني'],
    answerH: 'حارس المحفظة في فقرة واحدة',
    answer: 'حارس المحفظة مفتاح أمان مجاني داخل تطبيق WalletLens. تختار حتى ثلاثة أشخاص ومدة ٣٠ أو ٩٠ أو ١٨٠ يوما، وكلما فتحت WalletLens عاد العد من جديد. فإن انتهت المدة راسلك WalletLens أولا برابط "ما زلت هنا"، ولا يصل لورثتك شيء إلا إن لم ترد خلال ١٤ يوما، فتصلهم رسالتك الشخصية ورمز QR لأصولك وكمياتها وتكلفتها. ولا تُخزَّن المفاتيح الخاصة أو عبارات الاسترداد أو كلمات المرور ولا تُرسل أبدا.',
    facts: [['ما هو', 'مفتاح أمان لمحفظتك'], ['الورثة', 'حتى ٣ أشخاص عبر البريد'], ['المدة', '٣٠ أو ٩٠ أو ١٨٠ يوما'], ['شبكة الأمان', 'ننبهك أولا، والورثة بعد ١٤ يوما فقط'], ['ما يُرسل', 'رسالة ورمز QR للأصول والكميات والتكلفة'], ['ما لا يُرسل أبدا', 'المفاتيح وعبارات الاسترداد وكلمات المرور']],
    card: { title: 'حارس المحفظة', status: 'مفعّل', days: 'يوما متبقيا', reset: 'فتح WalletLens يعيد العداد تلقائيا', h1: 'سارة، الزوجة', h2: 'عمر، الابن', h3: 'ليلى، المحامية', r: 'رسالة ورمز QR', msg: 'رسالة شخصية، بلا مفاتيح أبدا' },
    howH: 'فعّله مرة. <em>وانسَه.</em>',
    howP: 'تضيع كل عام أموال في العملات الرقمية وحسابات الوساطة لأن أحدا لم يعلم بوجودها. الحارس يضمن أن يجد أحبابك ما تتركه لهم.',
    steps: [
      ['اختر ورثتك', 'أضف حتى ثلاثة أشخاص بالاسم والبريد واكتب لهم رسالة شخصية.'],
      ['حدد المدة', '٣٠ أو ٩٠ أو ١٨٠ يوما. كلما فتحت WalletLens بدأ العد من جديد.'],
      ['عش حياتك', 'درع في لوحتك يعرض الأيام المتبقية. لا شيء عليك تذكره.'],
    ],
    tlH: 'لا يُراسَل أحد <em>عن طريق الخطأ.</em>',
    tlP: 'فقدت هاتفك أو في سفر طويل؟ الحارس يسألك أولا عبر البريد ومن أي جهاز.',
    tl: [
      ['تغيب عن التطبيق', 'لم تفتح WalletLens طوال المدة التي اخترتها.'],
      ['نراسلك أولا', 'تنبيه برابط "ما زلت هنا" بضغطة واحدة من أي جهاز.'],
      ['١٤ يوما للرد', 'ضغطة واحدة ويُعاد كل شيء، ولا يعلم ورثتك بشيء.'],
      ['إبلاغ الورثة', 'عندها فقط تصلهم رسالتك ورمز المحفظة.'],
    ],
    shared: ['الأصول والكميات والتكلفة', 'رسالتك الشخصية'],
    never: ['المفاتيح الخاصة', 'عبارات الاسترداد', 'كلمات المرور'],
    fH: 'راحة بال <em>دون أن تكشف شيئا.</em>',
    feats: [
      ['shield', 'مفتاح أمان حقيقي', 'يعمل وحده في الخلفية، وفتحك للتطبيق هو تسجيل حضورك فلا يزعجك.'],
      ['mail', 'رسالة بكلماتك', 'حتى ٥٠٠ حرف لمن تحب، تصل مع محفظتك.'],
      ['qr', 'رمز QR للمحفظة', 'يمسحه الورثة ليروا كل أصل وكميته وتكلفته في WalletLens فلا يُنسى شيء.'],
      ['key', 'مفاتيحك لا تغادرك', 'الرمز يحمل لقطة للأصول فقط، بلا مفاتيح أو عبارات استرداد أو كلمات مرور.'],
      ['test', 'أرسل تجربة لنفسك', 'شاهد بالضبط ما سيصل لورثتك قبل أن تعتمد عليه.'],
      ['pause', 'ألغِ متى شئت', 'أوقفه أو عدّل الورثة من الإعدادات في أي وقت.'],
    ],
    faq: [
      ['ما هو مفتاح الأمان للعملات الرقمية؟', 'خدمة تعمل حين تتوقف عن تسجيل حضورك. يرسل حارس المحفظة رسالتك ورمز المحفظة لورثتك إن لم تفتح WalletLens مدة ٣٠ أو ٩٠ أو ١٨٠ يوما.'],
      ['ماذا يحدث لعملاتي الرقمية بعد وفاتي؟', 'تبقى أموالك في مكانها، لكن عائلتك لا تستطيع المطالبة بها إلا إن علمت بوجودها وأين هي. الحارس يعطيهم هذه الخريطة: كل أصل وكميته ومنصته، ليطالبوا به بالطريق الشرعي والقانوني.'],
      ['هل يحصل ورثتي على مفاتيحي الخاصة؟', 'لا. الحارس لا يخزن ولا يرسل المفاتيح أو عبارات الاسترداد أو كلمات المرور، بل يخبر عائلتك بما تملك وأين، وتبقى الحيازة كما هي.'],
      ['ماذا لو فقدت هاتفي أو سافرت؟', 'قبل مراسلة أي وارث نرسل لك تنبيها برابط "ما زلت هنا" يعمل من أي جهاز، ولا يُبلَّغ الورثة إلا إن لم ترد خلال ١٤ يوما.'],
      ['هل يشمل الأسهم والذهب والنقد؟', 'نعم، اللقطة تشمل كل ما في WalletLens: العملات الرقمية والأسهم والصناديق والذهب والنقد والعقار.'],
      ['هل حارس المحفظة مجاني؟', 'نعم، مجاني ودون أي حساب سوى عناوين البريد التي تختار إضافتها.'],
    ],
    note: 'حارس المحفظة ليس وصية ولا ينقل الملكية. استشر محاميا في شأن تركتك؛ والحارس يضمن أن تعرف عائلتك ما تطالب به.',
    endH: 'اترك لهم خريطة، <em>لا لغزا.</em>',
    endP: 'مجاني على الويب وأندرويد وويندوز وكروم، بالعربية والإنجليزية والفرنسية والإسبانية والألمانية والإيطالية.',
    howToName: 'كيف تجهز ميراث عملاتك الرقمية مع حارس المحفظة',
  },
  fr: {
    title: 'Portfolio Guardian : héritage crypto et dead man’s switch | WalletLens',
    desc: 'Un dead man’s switch gratuit pour vos placements. Si vous n’ouvrez plus WalletLens, vos héritiers reçoivent votre message et un QR de vos crypto, actions et or. Jamais vos clés.',
    keywords: 'héritage crypto, succession crypto, dead man’s switch crypto, que deviennent mes cryptos à ma mort, transmission actifs numériques, Portfolio Guardian',
    crumb: 'Portfolio Guardian',
    kick: 'Héritage crypto, simplement',
    h1: 'S’il vous arrive quelque chose, <em>votre famille saura.</em>',
    sub: 'Portfolio Guardian est un dead man’s switch pour vos placements. Si vous n’ouvrez plus WalletLens pendant 30, 90 ou 180 jours, les personnes choisies reçoivent votre message et un QR de votre portefeuille. Jamais vos clés ni vos mots de passe.',
    cta: 'Activer Guardian', cta2: 'Comment ça marche',
    trust: ['Jusqu’à 3 héritiers', 'Vous êtes prévenu d’abord', 'Aucune clé', 'Gratuit'],
    answerH: 'Portfolio Guardian en un paragraphe',
    answer: 'Portfolio Guardian est un dead man’s switch gratuit intégré à WalletLens. Vous désignez jusqu’à trois personnes et une durée de 30, 90 ou 180 jours. Chaque ouverture de WalletLens remet le compteur à zéro. S’il arrive à terme, WalletLens vous envoie d’abord un lien « Je suis toujours là » ; sans réponse sous 14 jours, vos héritiers reçoivent votre message et un QR de vos avoirs (actifs, quantités, prix de revient). Clés privées, phrases de récupération et mots de passe ne sont jamais stockés ni envoyés.',
    facts: [['Ce que c’est', 'Un dead man’s switch pour votre portefeuille'], ['Héritiers', 'Jusqu’à 3 personnes, par e-mail'], ['Durée', '30, 90 ou 180 jours'], ['Sécurité', 'Vous êtes prévenu d’abord, héritiers après 14 jours'], ['Partagé', 'Message et QR des actifs, quantités, prix de revient'], ['Jamais partagé', 'Clés, phrases de récupération, mots de passe']],
    card: { title: 'Portfolio Guardian', status: 'Actif', days: 'jours restants', reset: 'Ouvrir WalletLens remet le compteur à zéro', h1: 'Sara, épouse', h2: 'Omar, fils', h3: 'Layla, avocate', r: 'Message et QR', msg: 'Message personnel, jamais de clés' },
    howH: 'Réglez-le une fois. <em>Oubliez-le.</em>',
    howP: 'Chaque année, des comptes crypto et de courtage sont perdus parce que personne ne savait qu’ils existaient. Guardian veille à ce que vos proches trouvent ce que vous leur laissez.',
    steps: [
      ['Choisissez vos héritiers', 'Ajoutez jusqu’à trois personnes par nom et e-mail, et écrivez-leur un message.'],
      ['Choisissez une durée', '30, 90 ou 180 jours. À chaque ouverture de WalletLens, le compteur repart.'],
      ['Vivez votre vie', 'Un bouclier dans votre tableau de bord affiche les jours restants. Rien à retenir.'],
    ],
    tlH: 'Personne n’est jamais <em>contacté par erreur.</em>',
    tlP: 'Téléphone perdu ou long voyage ? Guardian vous demande toujours d’abord, par e-mail, depuis n’importe quel appareil.',
    tl: [
      ['Vous êtes silencieux', 'Vous n’avez pas ouvert WalletLens pendant la durée choisie.'],
      ['On vous écrit d’abord', 'Un avertissement avec un lien « Je suis toujours là » en un clic.'],
      ['14 jours pour répondre', 'Un clic et tout repart. Vos héritiers n’en savent rien.'],
      ['Héritiers prévenus', 'Alors seulement ils reçoivent votre message et le QR.'],
    ],
    shared: ['Actifs, quantités, prix de revient', 'Votre message personnel'],
    never: ['Clés privées', 'Phrases de récupération', 'Mots de passe'],
    fH: 'L’esprit tranquille, <em>sans rien livrer.</em>',
    feats: [
      ['shield', 'Un vrai dead man’s switch', 'Il tourne seul en arrière-plan. Ouvrir l’application suffit comme signe de vie, sans jamais vous déranger.'],
      ['mail', 'Un message à vous', 'Jusqu’à 500 caractères pour ceux que vous aimez, envoyés avec votre portefeuille.'],
      ['qr', 'QR du portefeuille', 'Vos héritiers le scannent pour voir chaque actif, quantité et prix de revient dans WalletLens.'],
      ['key', 'Vos clés restent à vous', 'Le QR ne contient qu’un instantané des avoirs. Jamais de clés, de phrases ni de mots de passe.'],
      ['test', 'Envoyez-vous un test', 'Voyez exactement ce que vos héritiers recevraient avant de compter dessus.'],
      ['pause', 'Annulable à tout moment', 'Désactivez-le ou modifiez vos héritiers dans les réglages quand vous voulez.'],
    ],
    faq: [
      ['Qu’est-ce qu’un dead man’s switch crypto ?', 'Un service qui se déclenche quand vous ne donnez plus signe de vie. Portfolio Guardian envoie à vos héritiers votre message et un QR du portefeuille si vous n’ouvrez plus WalletLens pendant 30, 90 ou 180 jours.'],
      ['Que deviennent mes cryptos à ma mort ?', 'Vos avoirs restent où ils sont, mais votre famille ne peut les réclamer que si elle sait qu’ils existent et où chercher. Guardian lui donne cette carte : chaque actif, quantité et plateforme, pour les réclamer par la voie légale.'],
      ['Mes héritiers auront-ils mes clés privées ?', 'Non. Guardian ne stocke ni n’envoie jamais de clés, phrases de récupération ou mots de passe. Il dit à votre famille ce que vous détenez et où.'],
      ['Et si je perds mon téléphone ou si je voyage ?', 'Avant de contacter un héritier, nous vous envoyons un lien « Je suis toujours là » utilisable depuis n’importe quel appareil. Vos héritiers ne sont prévenus que sans réponse sous 14 jours.'],
      ['Cela couvre-t-il actions, or et liquidités ?', 'Oui. L’instantané couvre tout ce qui est dans WalletLens : crypto, actions, fonds, or, liquidités et immobilier.'],
      ['Portfolio Guardian est-il gratuit ?', 'Oui, gratuit et sans compte, en dehors des adresses e-mail que vous ajoutez.'],
    ],
    note: 'Portfolio Guardian n’est pas un testament et ne transfère aucune propriété. Parlez de votre succession à un notaire ; Guardian veille à ce que votre famille sache quoi demander.',
    endH: 'Laissez une carte, <em>pas un mystère.</em>',
    endP: 'Gratuit sur le web, Android, Windows et Chrome. En français, anglais, arabe, espagnol, allemand et italien.',
    howToName: 'Comment préparer la transmission de vos cryptos avec Portfolio Guardian',
  },
  es: {
    title: 'Portfolio Guardian: herencia cripto y dead man’s switch | WalletLens',
    desc: 'Un dead man’s switch gratis para tus inversiones. Si dejas de abrir WalletLens, tus herederos reciben tu mensaje y un QR de tus cripto, acciones y oro. Nunca tus claves.',
    keywords: 'herencia cripto, herencia de criptomonedas, dead man’s switch cripto, qué pasa con mis criptomonedas si muero, herencia de activos digitales, Portfolio Guardian',
    crumb: 'Portfolio Guardian',
    kick: 'Herencia cripto, fácil',
    h1: 'Si te pasa algo, <em>tu familia lo sabrá.</em>',
    sub: 'Portfolio Guardian es un dead man’s switch para tus inversiones. Si dejas de abrir WalletLens durante 30, 90 o 180 días, las personas que elijas reciben tu mensaje y un QR de tu cartera. Nunca tus claves ni contraseñas.',
    cta: 'Activar Guardian', cta2: 'Cómo funciona',
    trust: ['Hasta 3 herederos', 'Te avisamos primero', 'Sin claves', 'Gratis'],
    answerH: 'Portfolio Guardian en un párrafo',
    answer: 'Portfolio Guardian es un dead man’s switch gratuito dentro de WalletLens. Eliges hasta tres personas y un plazo de 30, 90 o 180 días. Cada vez que abres WalletLens la cuenta atrás se reinicia. Si se agota, WalletLens primero te envía un enlace «Sigo aquí»; solo si no respondes en 14 días tus herederos reciben tu mensaje y un QR de tus activos (activos, cantidades y coste). Las claves privadas, frases semilla y contraseñas nunca se guardan ni se envían.',
    facts: [['Qué es', 'Un dead man’s switch para tu cartera'], ['Herederos', 'Hasta 3 personas, por email'], ['Plazo', '30, 90 o 180 días'], ['Seguridad', 'Te avisamos primero, herederos tras 14 días'], ['Se comparte', 'Mensaje y QR de activos, cantidades y coste'], ['Nunca se comparte', 'Claves, frases semilla, contraseñas']],
    card: { title: 'Portfolio Guardian', status: 'Activo', days: 'días restantes', reset: 'Abrir WalletLens reinicia la cuenta atrás', h1: 'Sara, esposa', h2: 'Omar, hijo', h3: 'Layla, abogada', r: 'Mensaje y QR', msg: 'Mensaje personal, nunca claves' },
    howH: 'Configúralo una vez. <em>Olvídate.</em>',
    howP: 'Cada año se pierden cuentas cripto y de bróker porque nadie sabía que existían. Guardian se asegura de que las personas que quieres encuentren lo que les dejas.',
    steps: [
      ['Elige tus herederos', 'Añade hasta tres personas con nombre y email, y escríbeles un mensaje personal.'],
      ['Elige un plazo', '30, 90 o 180 días. Cada vez que abres WalletLens, la cuenta empieza de nuevo.'],
      ['Vive tu vida', 'Un escudo en tu panel muestra los días restantes. No tienes que recordar nada.'],
    ],
    tlH: 'Nadie recibe nada <em>por error.</em>',
    tlP: '¿Perdiste el móvil o estás de viaje largo? Guardian siempre te pregunta primero, por email, desde cualquier dispositivo.',
    tl: [
      ['Dejas de entrar', 'No has abierto WalletLens durante el plazo elegido.'],
      ['Te escribimos primero', 'Un aviso con un enlace «Sigo aquí» de un clic que funciona en cualquier sitio.'],
      ['14 días para responder', 'Un clic y todo se reinicia. Tus herederos no se enteran de nada.'],
      ['Se avisa a los herederos', 'Solo entonces reciben tu mensaje y el QR de la cartera.'],
    ],
    shared: ['Activos, cantidades, coste', 'Tu mensaje personal'],
    never: ['Claves privadas', 'Frases semilla', 'Contraseñas'],
    fH: 'Tranquilidad, <em>sin entregar nada.</em>',
    feats: [
      ['shield', 'Un dead man’s switch real', 'Funciona solo en segundo plano. Abrir la app es tu señal de vida, así que nunca molesta.'],
      ['mail', 'Un mensaje con tus palabras', 'Hasta 500 caracteres para quienes quieres, enviados con tu cartera.'],
      ['qr', 'QR de la cartera', 'Tus herederos lo escanean para ver cada activo, cantidad y coste en WalletLens.'],
      ['key', 'Tus claves no salen de ti', 'El QR solo contiene una foto de tus activos. Nunca claves, frases semilla ni contraseñas.'],
      ['test', 'Envíate una prueba', 'Mira exactamente lo que recibirían tus herederos antes de confiar en ello.'],
      ['pause', 'Cancela cuando quieras', 'Desactívalo o cambia tus herederos en Ajustes cuando quieras.'],
    ],
    faq: [
      ['¿Qué es un dead man’s switch cripto?', 'Un servicio que actúa cuando dejas de dar señales de vida. Portfolio Guardian envía a tus herederos tu mensaje y un QR de la cartera si no abres WalletLens durante 30, 90 o 180 días.'],
      ['¿Qué pasa con mis cripto si muero?', 'Tus activos siguen donde están, pero tu familia solo puede reclamarlos si sabe que existen y dónde buscar. Guardian les da ese mapa: cada activo, cantidad y plataforma, para reclamarlo por la vía legal.'],
      ['¿Recibirán mis herederos mis claves privadas?', 'No. Guardian nunca guarda ni envía claves, frases semilla ni contraseñas. Le dice a tu familia qué tienes y dónde.'],
      ['¿Y si pierdo el móvil o me voy de viaje?', 'Antes de avisar a ningún heredero te enviamos un enlace «Sigo aquí» que funciona desde cualquier dispositivo. Solo se avisa a tus herederos si no respondes en 14 días.'],
      ['¿Incluye acciones, oro y efectivo?', 'Sí. La foto incluye todo lo que hay en WalletLens: cripto, acciones, fondos, oro, efectivo e inmuebles.'],
      ['¿Portfolio Guardian es gratis?', 'Sí, gratis y sin cuenta, aparte de los emails que decidas añadir.'],
    ],
    note: 'Portfolio Guardian no es un testamento ni transfiere la propiedad. Habla con un abogado sobre tu herencia; Guardian se asegura de que tu familia sepa qué reclamar.',
    endH: 'Deja un mapa, <em>no un misterio.</em>',
    endP: 'Gratis en la web, Android, Windows y Chrome. En español, inglés, árabe, francés, alemán e italiano.',
    howToName: 'Cómo preparar la herencia de tus cripto con Portfolio Guardian',
  },
  de: {
    title: 'Portfolio Guardian: Krypto-Erbe & Totmannschalter | WalletLens',
    desc: 'Ein kostenloser Totmannschalter für Ihr Vermögen. Öffnen Sie WalletLens nicht mehr, erhalten Ihre Erben Ihre Nachricht und einen QR-Code Ihrer Krypto, Aktien und Gold. Nie Ihre Schlüssel.',
    keywords: 'Krypto-Erbe, Kryptowährung vererben, Totmannschalter Krypto, was passiert mit meinen Kryptos wenn ich sterbe, digitaler Nachlass, Portfolio Guardian',
    crumb: 'Portfolio Guardian',
    kick: 'Krypto-Erbe, ganz einfach',
    h1: 'Wenn Ihnen etwas zustößt, <em>weiß Ihre Familie Bescheid.</em>',
    sub: 'Portfolio Guardian ist ein Totmannschalter für Ihr Vermögen. Öffnen Sie WalletLens 30, 90 oder 180 Tage nicht, erhalten die Menschen Ihrer Wahl Ihre Nachricht und einen QR-Code Ihres Portfolios. Nie Ihre Schlüssel oder Passwörter.',
    cta: 'Guardian aktivieren', cta2: 'So funktioniert es',
    trust: ['Bis zu 3 Erben', 'Sie werden zuerst gewarnt', 'Keine Schlüssel', 'Kostenlos'],
    answerH: 'Portfolio Guardian in einem Absatz',
    answer: 'Portfolio Guardian ist ein kostenloser Totmannschalter in der WalletLens App. Sie benennen bis zu drei Personen und wählen 30, 90 oder 180 Tage. Jedes Öffnen von WalletLens setzt den Countdown zurück. Läuft er ab, schickt WalletLens zuerst Ihnen einen Link „Ich bin noch da“; erst wenn Sie 14 Tage nicht reagieren, erhalten Ihre Erben Ihre Nachricht und einen QR-Code Ihrer Bestände (Werte, Mengen, Einstandspreis). Private Schlüssel, Seed-Phrasen und Passwörter werden nie gespeichert oder gesendet.',
    facts: [['Was es ist', 'Ein Totmannschalter für Ihr Portfolio'], ['Erben', 'Bis zu 3 Personen, per E-Mail'], ['Intervall', '30, 90 oder 180 Tage'], ['Sicherheitsnetz', 'Sie zuerst, Erben erst nach 14 Tagen'], ['Geteilt', 'Nachricht und QR mit Werten, Mengen, Einstandspreis'], ['Nie geteilt', 'Schlüssel, Seed-Phrasen, Passwörter']],
    card: { title: 'Portfolio Guardian', status: 'Aktiv', days: 'Tage übrig', reset: 'Das Öffnen von WalletLens setzt den Countdown zurück', h1: 'Sara, Ehefrau', h2: 'Omar, Sohn', h3: 'Layla, Anwältin', r: 'Nachricht und QR', msg: 'Persönliche Nachricht, nie Schlüssel' },
    howH: 'Einmal einrichten. <em>Vergessen.</em>',
    howP: 'Jedes Jahr gehen Krypto- und Depotkonten verloren, weil niemand von ihnen wusste. Guardian sorgt dafür, dass Ihre Liebsten finden, was Sie hinterlassen.',
    steps: [
      ['Erben wählen', 'Fügen Sie bis zu drei Personen mit Name und E-Mail hinzu und schreiben Sie ihnen eine Nachricht.'],
      ['Intervall wählen', '30, 90 oder 180 Tage. Jedes Öffnen von WalletLens startet den Countdown neu.'],
      ['Leben Sie Ihr Leben', 'Ein Schild im Dashboard zeigt die verbleibenden Tage. Sie müssen an nichts denken.'],
    ],
    tlH: 'Niemand wird <em>versehentlich benachrichtigt.</em>',
    tlP: 'Handy verloren oder lange auf Reisen? Guardian fragt immer zuerst Sie, per E-Mail, von jedem Gerät.',
    tl: [
      ['Sie melden sich nicht', 'Sie haben WalletLens im gewählten Zeitraum nicht geöffnet.'],
      ['Zuerst schreiben wir Ihnen', 'Eine Warnung mit einem Link „Ich bin noch da“, der überall funktioniert.'],
      ['14 Tage zum Antworten', 'Ein Klick und alles startet neu. Ihre Erben erfahren nichts.'],
      ['Erben werden informiert', 'Erst dann erhalten sie Ihre Nachricht und den QR-Code.'],
    ],
    shared: ['Werte, Mengen, Einstandspreis', 'Ihre persönliche Nachricht'],
    never: ['Private Schlüssel', 'Seed-Phrasen', 'Passwörter'],
    fH: 'Ruhe im Kopf, <em>ohne etwas preiszugeben.</em>',
    feats: [
      ['shield', 'Ein echter Totmannschalter', 'Läuft von selbst im Hintergrund. Das Öffnen der App ist Ihr Lebenszeichen, ganz ohne Nachfragen.'],
      ['mail', 'Eine Nachricht in Ihren Worten', 'Bis zu 500 Zeichen für Ihre Liebsten, zusammen mit Ihrem Portfolio.'],
      ['qr', 'Scannbarer Portfolio-QR', 'Ihre Erben scannen ihn und sehen jeden Wert, jede Menge und den Einstandspreis in WalletLens.'],
      ['key', 'Schlüssel bleiben bei Ihnen', 'Der QR enthält nur eine Momentaufnahme der Bestände. Nie Schlüssel, Seed-Phrasen oder Passwörter.'],
      ['test', 'Test an sich selbst', 'Sehen Sie genau, was Ihre Erben erhalten würden, bevor Sie sich darauf verlassen.'],
      ['pause', 'Jederzeit kündbar', 'Schalten Sie es aus oder ändern Sie Ihre Erben jederzeit in den Einstellungen.'],
    ],
    faq: [
      ['Was ist ein Krypto-Totmannschalter?', 'Ein Dienst, der handelt, wenn Sie sich nicht mehr melden. Portfolio Guardian sendet Ihren Erben Ihre Nachricht und einen Portfolio-QR, wenn Sie WalletLens 30, 90 oder 180 Tage nicht öffnen.'],
      ['Was passiert mit meinen Kryptos, wenn ich sterbe?', 'Ihre Werte bleiben, wo sie sind, aber Ihre Familie kann sie nur beanspruchen, wenn sie davon weiß und weiß, wo sie suchen muss. Guardian gibt ihr diese Karte: jeden Wert, jede Menge und Plattform, für den rechtlichen Weg.'],
      ['Bekommen meine Erben meine privaten Schlüssel?', 'Nein. Guardian speichert oder sendet nie Schlüssel, Seed-Phrasen oder Passwörter. Es sagt Ihrer Familie, was Sie besitzen und wo.'],
      ['Was, wenn ich mein Handy verliere oder verreise?', 'Bevor ein Erbe kontaktiert wird, schicken wir Ihnen einen Link „Ich bin noch da“, der auf jedem Gerät funktioniert. Erben werden erst informiert, wenn Sie 14 Tage nicht reagieren.'],
      ['Sind Aktien, Gold und Bargeld dabei?', 'Ja. Die Momentaufnahme umfasst alles in WalletLens: Krypto, Aktien, Fonds, Gold, Bargeld und Immobilien.'],
      ['Ist Portfolio Guardian kostenlos?', 'Ja, kostenlos und ohne Konto, abgesehen von den E-Mail-Adressen, die Sie hinzufügen.'],
    ],
    note: 'Portfolio Guardian ist kein Testament und überträgt kein Eigentum. Sprechen Sie mit einem Anwalt oder Notar über Ihren Nachlass; Guardian sorgt dafür, dass Ihre Familie weiß, wonach sie fragen muss.',
    endH: 'Hinterlassen Sie eine Karte, <em>kein Rätsel.</em>',
    endP: 'Kostenlos im Web, für Android, Windows und Chrome. Auf Deutsch, Englisch, Arabisch, Französisch, Spanisch und Italienisch.',
    howToName: 'So richten Sie Ihr Krypto-Erbe mit Portfolio Guardian ein',
  },
  it: {
    title: 'Portfolio Guardian: eredità crypto e dead man’s switch | WalletLens',
    desc: 'Un dead man’s switch gratuito per i tuoi investimenti. Se smetti di aprire WalletLens, i tuoi eredi ricevono il tuo messaggio e un QR di cripto, azioni e oro. Mai le tue chiavi.',
    keywords: 'eredità crypto, successione criptovalute, dead man’s switch crypto, cosa succede alle mie cripto quando muoio, eredità digitale, Portfolio Guardian',
    crumb: 'Portfolio Guardian',
    kick: 'Eredità crypto, semplice',
    h1: 'Se ti succede qualcosa, <em>la tua famiglia lo saprà.</em>',
    sub: 'Portfolio Guardian è un dead man’s switch per i tuoi investimenti. Se non apri WalletLens per 30, 90 o 180 giorni, le persone che scegli ricevono il tuo messaggio e un QR del portafoglio. Mai le tue chiavi o password.',
    cta: 'Attiva Guardian', cta2: 'Come funziona',
    trust: ['Fino a 3 eredi', 'Avvisiamo prima te', 'Nessuna chiave', 'Gratis'],
    answerH: 'Portfolio Guardian in un paragrafo',
    answer: 'Portfolio Guardian è un dead man’s switch gratuito dentro WalletLens. Scegli fino a tre persone e un intervallo di 30, 90 o 180 giorni. Ogni volta che apri WalletLens il conto alla rovescia riparte. Se scade, WalletLens prima ti invia un link «Ci sono ancora»; solo se non rispondi entro 14 giorni i tuoi eredi ricevono il tuo messaggio e un QR dei tuoi beni (asset, quantità, prezzo di carico). Chiavi private, seed phrase e password non vengono mai salvate né inviate.',
    facts: [['Che cos’è', 'Un dead man’s switch per il tuo portafoglio'], ['Eredi', 'Fino a 3 persone, via email'], ['Intervallo', '30, 90 o 180 giorni'], ['Sicurezza', 'Avvisiamo prima te, gli eredi dopo 14 giorni'], ['Condiviso', 'Messaggio e QR di asset, quantità, prezzo di carico'], ['Mai condiviso', 'Chiavi, seed phrase, password']],
    card: { title: 'Portfolio Guardian', status: 'Attivo', days: 'giorni rimasti', reset: 'Aprire WalletLens fa ripartire il conto alla rovescia', h1: 'Sara, moglie', h2: 'Omar, figlio', h3: 'Layla, avvocata', r: 'Messaggio e QR', msg: 'Messaggio personale, mai chiavi' },
    howH: 'Impostalo una volta. <em>Dimenticalo.</em>',
    howP: 'Ogni anno si perdono conti cripto e di trading perché nessuno sapeva che esistessero. Guardian fa sì che chi ami trovi ciò che gli lasci.',
    steps: [
      ['Scegli i tuoi eredi', 'Aggiungi fino a tre persone con nome ed email, e scrivi loro un messaggio personale.'],
      ['Scegli un intervallo', '30, 90 o 180 giorni. Ogni volta che apri WalletLens, il conto riparte.'],
      ['Vivi la tua vita', 'Uno scudo nella dashboard mostra i giorni rimasti. Non devi ricordare nulla.'],
    ],
    tlH: 'Nessuno viene <em>contattato per errore.</em>',
    tlP: 'Telefono perso o un lungo viaggio? Guardian chiede sempre prima a te, via email, da qualsiasi dispositivo.',
    tl: [
      ['Non ti fai sentire', 'Non hai aperto WalletLens per l’intervallo scelto.'],
      ['Scriviamo prima a te', 'Un avviso con un link «Ci sono ancora» che funziona ovunque.'],
      ['14 giorni per rispondere', 'Un clic e tutto riparte. I tuoi eredi non sapranno nulla.'],
      ['Gli eredi vengono avvisati', 'Solo allora ricevono il tuo messaggio e il QR del portafoglio.'],
    ],
    shared: ['Asset, quantità, prezzo di carico', 'Il tuo messaggio personale'],
    never: ['Chiavi private', 'Seed phrase', 'Password'],
    fH: 'Serenità, <em>senza cedere nulla.</em>',
    feats: [
      ['shield', 'Un vero dead man’s switch', 'Funziona da solo in background. Aprire l’app è il tuo segnale di vita, senza mai disturbarti.'],
      ['mail', 'Un messaggio con le tue parole', 'Fino a 500 caratteri per chi ami, inviati con il tuo portafoglio.'],
      ['qr', 'QR del portafoglio', 'I tuoi eredi lo scansionano per vedere ogni asset, quantità e prezzo di carico in WalletLens.'],
      ['key', 'Le chiavi restano a te', 'Il QR contiene solo una fotografia dei beni. Mai chiavi, seed phrase o password.'],
      ['test', 'Inviati un test', 'Vedi esattamente cosa riceverebbero i tuoi eredi prima di affidartici.'],
      ['pause', 'Annulla quando vuoi', 'Disattivalo o modifica gli eredi nelle Impostazioni quando vuoi.'],
    ],
    faq: [
      ['Che cos’è un dead man’s switch per cripto?', 'Un servizio che interviene quando smetti di dare segni di vita. Portfolio Guardian invia ai tuoi eredi il tuo messaggio e un QR del portafoglio se non apri WalletLens per 30, 90 o 180 giorni.'],
      ['Cosa succede alle mie cripto quando muoio?', 'I tuoi beni restano dove sono, ma la tua famiglia può reclamarli solo se sa che esistono e dove cercarli. Guardian le dà questa mappa: ogni asset, quantità e piattaforma, per reclamarli per vie legali.'],
      ['I miei eredi riceveranno le mie chiavi private?', 'No. Guardian non salva né invia mai chiavi, seed phrase o password. Dice alla tua famiglia cosa possiedi e dove.'],
      ['E se perdo il telefono o sono in viaggio?', 'Prima di contattare un erede ti inviamo un link «Ci sono ancora» che funziona da qualsiasi dispositivo. Gli eredi vengono avvisati solo se non rispondi entro 14 giorni.'],
      ['Copre anche azioni, oro e contanti?', 'Sì. La fotografia include tutto ciò che è in WalletLens: cripto, azioni, fondi, oro, contanti e immobili.'],
      ['Portfolio Guardian è gratis?', 'Sì, gratis e senza account, a parte gli indirizzi email che scegli di aggiungere.'],
    ],
    note: 'Portfolio Guardian non è un testamento e non trasferisce la proprietà. Parla con un notaio della tua successione; Guardian fa sì che la tua famiglia sappia cosa chiedere.',
    endH: 'Lascia una mappa, <em>non un mistero.</em>',
    endP: 'Gratis sul web, Android, Windows e Chrome. In italiano, inglese, arabo, francese, spagnolo e tedesco.',
    howToName: 'Come preparare l’eredità delle tue cripto con Portfolio Guardian',
  },
}
