package live.walletlens.twa;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;

/**
 * A copy of the user's portfolio, held in the APP's own storage.
 *
 * <h3>Why this exists</h3>
 *
 * WalletLens is a Trusted Web Activity, which means the app IS Chrome: the page
 * renders in a Custom Tab and everything it saves goes into Chrome's storage
 * for the walletlens.live origin, inside Chrome's sandbox. Two consequences
 * that users experience as the app losing their data:
 *
 * <ul>
 *   <li>"Clear browsing data" in Chrome deletes the entire portfolio. Nothing
 *       warns that a browser setting will empty an app that is not obviously a
 *       browser.</li>
 *   <li>Android's own Settings → Apps → WalletLens → Clear storage does the
 *       opposite: it wipes this app's data and leaves the portfolio untouched,
 *       because the portfolio was never here. (ManageDataLauncherActivity in
 *       the manifest exists to soften exactly that confusion.)</li>
 * </ul>
 *
 * <p>The portfolio is also outside Android's app backup, which only ever sees
 * this package's own directory.
 *
 * <p>So the web app mirrors itself here. This is a SECOND copy, not a move:
 * making the app the primary store would mean rendering in a WebView instead
 * of a TWA, which costs Web Push (no service worker push in a WebView), Google
 * Drive sign-in (Google refuses OAuth in WebViews) and, worst, every existing
 * user's data — a WebView cannot read what Chrome has stored.
 *
 * <h3>The payload</h3>
 *
 * A {@code WL3-} backup code: the same gzipped, base64 string the Settings
 * backup screen produces, generated by the same function. Deliberately opaque
 * to this class — it is stored and handed back verbatim, and the web side owns
 * both ends of the format. A thousand-transaction portfolio is around thirty
 * kilobytes once compressed.
 *
 * <h3>Getting it back</h3>
 *
 * Native code cannot write into Chrome's storage, and a TWA has no JavaScript
 * bridge — that is the point of it being a real browser. The one channel that
 * exists is the launch URL, so a restore relaunches the app with the payload in
 * the URL's FRAGMENT.
 *
 * <p>The fragment, specifically, and not a query parameter: fragments are never
 * sent to the server. The portfolio stays on the device, which is the whole
 * promise of this app, and the web side strips it from the URL as soon as it
 * has read it.
 */
public class DataVaultActivity extends Activity {

    private static final String TAG = "WalletLensVault";

    /** walletlens://vault-save?data=WL3-... */
    private static final String HOST_SAVE = "vault-save";
    /** walletlens://vault-restore */
    private static final String HOST_RESTORE = "vault-restore";

    private static final String VAULT_FILE = "portfolio-vault.wl3";

    /**
     * Refuse anything larger than this.
     *
     * <p>Not a disk limit — it is the restore path that cannot grow without
     * bound. Handing the payload back means putting it on a URL inside an
     * Intent, and Intents cross a Binder transaction with a hard ceiling of
     * about a megabyte for the whole process. A vault that saved successfully
     * and could never be handed back would be worse than one that refused the
     * save, because the failure would only surface on the day it was needed.
     *
     * <p>Half a megabyte of gzipped base64 is a portfolio far larger than any
     * this app has seen; the file export in Settings has no such limit and
     * remains the answer for one that exceeds it.
     */
    private static final int MAX_PAYLOAD_BYTES = 512 * 1024;

    /** Where a restore sends the user back to. */
    private static final String RESTORE_URL = "https://walletlens.live/dashboard";

    /** Fragment key the web app reads the payload out of. */
    private static final String FRAGMENT_KEY = "wlvault";

    /** Fragment value meaning "there was nothing stored", so the web can say so. */
    private static final String EMPTY_MARKER = "empty";

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Uri data = getIntent() != null ? getIntent().getData() : null;
        String host = data != null ? data.getHost() : null;

        try {
            if (HOST_SAVE.equals(host)) {
                save(data);
            } else if (HOST_RESTORE.equals(host)) {
                restore();
                return;   // restore() starts the launcher; do not finish twice
            } else {
                Log.w(TAG, "Unknown vault host: " + host);
            }
        } catch (Throwable e) {
            // A vault that throws must not take the app down with it. This is a
            // safety net; failing to write one is not worth a crash dialog on
            // top of whatever the user was actually doing.
            Log.w(TAG, "vault operation failed: " + e);
        }

        finish();
    }

    // ── Save ─────────────────────────────────────────────────────────────

    private void save(@NonNull Uri data) {
        String payload;
        try {
            payload = data.getQueryParameter("data");
        } catch (UnsupportedOperationException e) {
            Log.w(TAG, "opaque vault URI, no data to read");
            return;
        }
        write(this, payload);
    }

    /**
     * Store a backup code, atomically.
     *
     * <p>Static and Context-taking so the WebView shell's JavaScript bridge can
     * call it directly. Under the TWA the only way in was this Activity
     * catching an intent, which could not report whether it worked; through the
     * bridge the same code path returns a boolean the web app can act on.
     *
     * @return whether the vault now holds this payload
     */
    static boolean write(@NonNull Context context, @Nullable String payload) {
        if (payload == null || payload.isEmpty()) {
            Log.w(TAG, "vault save with no payload");
            return false;
        }

        // Only the format this app produces. The intent filter is exported —
        // it has to be, because the page that sends it runs in Chrome's
        // process — so any installed app can call this. It cannot read the
        // vault back (there is no read intent, only a restore that relaunches
        // OUR launcher at OUR origin), but without this check it could
        // overwrite the vault with rubbish and destroy the backup silently.
        if (!payload.startsWith("WL3-") && !payload.startsWith("WL1-")) {
            Log.w(TAG, "refusing a vault payload that is not a backup code");
            return false;
        }

        byte[] bytes = payload.getBytes(StandardCharsets.UTF_8);
        if (bytes.length > MAX_PAYLOAD_BYTES) {
            Log.w(TAG, "vault payload too large to be restorable: " + bytes.length);
            return false;
        }

        // Written to a temporary file and renamed. A half-written vault is
        // worse than no vault: it looks present, restores as corrupt, and does
        // so at the one moment the user has nothing else left. Rename is
        // atomic on the same filesystem, so the real file is either the old
        // one or the complete new one, never a partial write.
        File dir = context.getFilesDir();
        File tmp = new File(dir, VAULT_FILE + ".tmp");
        File out = new File(dir, VAULT_FILE);

        try (OutputStreamWriter w =
                     new OutputStreamWriter(new FileOutputStream(tmp), StandardCharsets.UTF_8)) {
            w.write(payload);
            w.flush();
        } catch (IOException e) {
            Log.w(TAG, "vault write failed: " + e.getMessage());
            //noinspection ResultOfMethodCallIgnored
            tmp.delete();
            return false;
        }

        if (!tmp.renameTo(out)) {
            Log.w(TAG, "vault rename failed; keeping the previous copy");
            //noinspection ResultOfMethodCallIgnored
            tmp.delete();
            return false;
        }

        Log.d(TAG, "vault saved, " + bytes.length + " bytes");
        return true;
    }

    // ── Restore ──────────────────────────────────────────────────────────

    private void restore() {
        String payload = read(this);
        String fragment = FRAGMENT_KEY + "="
                + (payload != null && !payload.isEmpty() ? Uri.encode(payload) : EMPTY_MARKER);

        // Back into the app, carrying the payload where the network will never
        // see it. deepLink drops a URL that is not ours, and RESTORE_URL is
        // ours, so the fragment is appended after the check rather than being
        // offered up to it — a fragment is not part of what "ours" means and a
        // portfolio has no business being parsed as a host.
        Intent i = AppEntry.deepLink(this, RESTORE_URL);
        i.setData(Uri.parse(RESTORE_URL + "#" + fragment));
        startActivity(i);
        finish();
    }

    // ── Helpers, also used from Settings diagnostics ──────────────────────

    /** The stored backup code, or null when there is none. */
    @Nullable
    static String read(@NonNull Context context) {
        File f = new File(context.getFilesDir(), VAULT_FILE);
        if (!f.isFile() || f.length() == 0) return null;
        try (InputStream in = new java.io.FileInputStream(f)) {
            ByteArrayOutputStream buf = new ByteArrayOutputStream();
            byte[] chunk = new byte[8192];
            int n;
            while ((n = in.read(chunk)) > 0) buf.write(chunk, 0, n);
            return new String(buf.toByteArray(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            Log.w(TAG, "vault read failed: " + e.getMessage());
            return null;
        }
    }
}
